
#ukuran layar
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# MINIMIZE_WIDTH = SCREEN_WIDTH * 2 // 3
# MINIMIZE_HEIGHT = SCREEN_HEIGHT * 2 // 3

FPS = 60

TITLE = "SobiRun"
TITLE_SCREEN = "assets/images/ltg.png"